# Generated by Django 5.2.5 on 2025-08-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_user_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='tts-medical', max_length=10),
        ),
    ]
