# Generated by Django 5.2.5 on 2025-09-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_question_question_text_alter_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default='Subject', on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
    ]
